spring:
  application:
    name: spring-mentor-162

  datasource:
    url: jdbc:postgresql://localhost:5432/java162
    username: postgres
    password: 12345


  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: matrix




